[package]
name = "vrc-log"
version = "0.2.4"
authors = ["Shayne Hartford <shaybox@shaybox.com>"]
edition = "2021"
description = "VRChat Local Cache Avatar ID Logger"
readme = "README.md"
repository = "https://github.com/ShayBox/VRC-LOG"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
colored = "2"
discord-presence = "0.5"
lazy_static = "1"
notify = { git = "https://github.com/notify-rs/notify.git", version = "6" }
regex = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlite = { version = "0.31", features = ["bundled"] }

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
