[package]
name = "vrc-log"
version = "0.2.2"
authors = ["Shayne Hartford <shaybox@shaybox.com>"]
edition = "2021"
description = "VRChat Local Cache Avatar ID Logger"
readme = "README.md"
repository = "https://github.com/ShayBox/VRC-LOG"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
discord-presence = "0.5"
lazy_static = "1"
notify = { git = "https://github.com/notify-rs/notify.git", version = "6" }
regex = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlite = { version = "0.31", features = ["bundled"] }
